/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yakult;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author xavier
 */
public class Fondo extends javax.swing.JPanel {
//private Image fondo;
    public Fondo() {
        initComponents();
        this.setSize(814,419);
    }
//    private void preInit()
//    {
//        fondo = new ImageIcon(1.png);
//    }
public void paintComponent(Graphics g)
{
    Dimension tam= getSize();
    ImageIcon imgFondo=new ImageIcon(new ImageIcon(getClass().getResource("/yakult/1.png")).getImage());
    g.drawImage(imgFondo.getImage(), 0, 0, tam.width,tam.height,null);
    setOpaque(false);
    super.paintComponent(g);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
